### ISSUE TITLE
import_feed crashes if there is no title_detail

### ISSUE THREAD

**Issue by jjconti** [getnikola/nikola#1963]
I tried it with 2 "feeds":

* http://feeds.feedburner.com/EnElExilio
* http://www.juanjoconti.com.ar/categoria/gnu-linux/feed/

The traceback is similar:

    Traceback (most recent call last):
      File "/Users/juanjo/nikola/lib/python2.7/site-packages/doit/doit_cmd.py", line 165, in run
        return command.parse_execute(args)
      File "/Users/juanjo/nikola/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
        return self.execute(params, args)
      File "/Users/juanjo/nikola/lib/python2.7/site-packages/nikola/plugin_categories.py", line 127, in execute
        return self._execute(options, args)
      File "/Users/juanjo/nikola/lugcos/plugins/import_feed/import_feed.py", line 78, in _execute
        self.context = self.populate_context(channel)
      File "/Users/juanjo/nikola/lugcos/plugins/import_feed/import_feed.py", line 96, in populate_context
        if channel.feed.title_detail.language else 'en'
      File "/Users/juanjo/nikola/lib/python2.7/site-packages/feedparser.py", line 400, in __getattr__
        raise AttributeError, "object has no attribute '%s'" % key
    AttributeError: object has no attribute 'title_detail'

**Comment by ralsina** [comment]
In both cases it imported without crashing here.

Are you importing them into an existing site?

**Comment by jjconti** [comment]
Yes.

**Comment by ralsina** [comment]
Then it's probably triggered by the configuration... can you pastebin the conf.py somewhere, assuming it has no private information?

**Comment by jjconti** [comment]
Barely changed from default config http://pastebin.com/XGQnNMQU

**Comment by ralsina** [comment]
Still can't reproduce. Can you show me the whole thing you do? Commands, etc.

**Comment by jjconti** [comment]
I have some warnings:

    ~/nikola/lugcos$ nikola import_feed feed_url http://www.juanjoconti.com.ar/categoria/gnu-linux/feed/
    [2015-08-22T17:11:54Z] WARNING: ShimWarning: /Users/juanjo/nikola/lib/python2.7/site-packages/IPython/nbconvert.py:13: The `IPython.nbconvert` package has been deprecated. You should import from ipython_nbconvert instead.
    [2015-08-22T17:11:54Z] WARNING: ShimWarning: /Users/juanjo/nikola/lib/python2.7/site-packages/IPython/nbformat.py:13: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
    [2015-08-22T17:11:54Z] WARNING: ShimWarning: /Users/juanjo/nikola/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
    [2015-08-22T17:11:54Z] WARNING: ShimWarning: /Users/juanjo/nikola/lib/python2.7/site-packages/IPython/config.py:13: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
    Traceback (most recent call last):
      File "/Users/juanjo/nikola/lib/python2.7/site-packages/doit/doit_cmd.py", line 165, in run
        return command.parse_execute(args)
      File "/Users/juanjo/nikola/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
        return self.execute(params, args)
      File "/Users/juanjo/nikola/lib/python2.7/site-packages/nikola/plugin_categories.py", line 127, in execute
        return self._execute(options, args)
      File "/Users/juanjo/nikola/lugcos/plugins/import_feed/import_feed.py", line 78, in _execute
        self.context = self.populate_context(channel)
      File "/Users/juanjo/nikola/lugcos/plugins/import_feed/import_feed.py", line 96, in populate_context
        if channel.feed.title_detail.language else 'en'
      File "/Users/juanjo/nikola/lib/python2.7/site-packages/feedparser.py", line 400, in __getattr__
        raise AttributeError, "object has no attribute '%s'" % key
    AttributeError: object has no attribute 'title_detail'

**Comment by ralsina** [comment]
@jjconti try 

```
nikola import_feed http://www.juanjoconti.com.ar/categoria/gnu-linux/feed/
```

It will import into a new_site folder but then you can move the posts into the right place.

**Comment by jjconti** [comment]
Worked. Can I move them to posts/imported/ but in the site show them in the same level than the new ones? I think @humitos does this with this wordpress posts.

**Comment by ralsina** [comment]
Put them anywhere, it should "just work", as long as you have the HTML  compiler enabled and the right wildcard in your POSTS and PAGES settings.

**Comment by jjconti** [comment]
Done!

**Comment by ralsina** [comment]
Both work with import_feed v0.2
