### ISSUE TITLE
`nikola build` fails with `base-jinja` theme and no `COMMENT_SYSTEM`

### ISSUE THREAD

**Issue by clayadavis** [getnikola/nikola#3569]
### Environment

**Python Version:** 3.9

**Nikola Version:** master

**Operating System:** Pop!_OS 21.04

### Description:

In the current `master` (67fe01f44), sites using `base-jinja` and derived themes can fail to build when no comment system is used. The `nikola build` command fails with the following exception:

    jinja2.exceptions.UndefinedError: 'jinja2.environment.TemplateModule object' has no attribute 'comment_link_script'

[Full traceback](https://gist.github.com/clayadavis/c42e58894c5e97cad123b4cbe870e652). 

Git bisect suggests this bug was introduced with commit 251a3b2ad09e70a3701c089cee740f472fdccb95

#### Steps to reproduce

* Check out `nikola@67fe01f44`
* Build a demo site without comments, either leaving the commenting system blank in the interactive prompts or setting `COMMENT_SYSTEM = ""` in `conf.py`
* Set `THEME = "base-jinja"` in `conf.py`; child themes such as `bootstrap4-jinja` are also affected.
* Run `nikola build`
