### ISSUE TITLE
Installing themes does not work in Python 2.6

### ISSUE THREAD

**Issue by svisser** [getnikola/nikola#1298]
Installing a theme fails in Python 2.6 as instances of `ZipFile` do not have an `__exit__` attribute. Example:

```
nikola install_theme zen-jinja
```

fails with:

```
  File "/home/simeon/.virtualenvs/site/lib/python2.6/site-packages/nikola/plugins/command/install_theme.py", line 121, in _execute
    installstatus = self.do_install(name, data)
  File "/home/simeon/.virtualenvs/site/lib/python2.6/site-packages/nikola/plugins/command/install_theme.py", line 143, in do_install
    utils.extract_all(zip_file)
  File "/home/simeon/.virtualenvs/site/lib/python2.6/site-packages/nikola/utils.py", line 725, in extract_all
    with zip(zipfile) as z:
AttributeError: ZipFile instance has no attribute '__exit__'
```

This can be confirmed in the docs as the ability to use ZipFile as context manager was added in Python 2.7: https://docs.python.org/2/library/zipfile.html.

I am using Nikola 7.0.0.
