### ISSUE TITLE
Planetoid is no longer working in  Nikola 6.4.0

### ISSUE THREAD

**Issue by flexiondotorg** [getnikola/nikola#1190]
Hi,

I just tried upgrading my Nikola instance and noticed that the Planetoid plugin no longer works. Here is the log from `nikola build`.

```
$ nikola build
[2014-03-31T10:06:41Z] WARNING: Nikola: Could not guess locale for language en, using locale C
ERROR:yapsy:Unable to import plugin: /home/martin/Snakepit/nikola-640/local/lib/python2.7/site-packages/nikola/plugins/command/planetoid
Traceback (most recent call last):
  File "/home/martin/Snakepit/nikola-640/local/lib/python2.7/site-packages/yapsy/PluginManager.py", line 483, in loadPlugins
    candidate_module = imp.load_module(plugin_module_name,None,candidate_filepath,("py","r",imp.PKG_DIRECTORY))
  File "/home/martin/Snakepit/nikola-640/local/lib/python2.7/site-packages/nikola/plugins/command/planetoid/__init__.py", line 60, in <module>
    class Entry(peewee.Model):
  File "/home/martin/Snakepit/nikola-640/local/lib/python2.7/site-packages/nikola/plugins/command/planetoid/__init__.py", line 63, in Entry
    content = peewee.TextField(max_length=20000)
TypeError: __init__() got an unexpected keyword argument 'max_length'
Scanning posts..done!
.  render_pages:/tmp/planetpi.org/output/plan/index.html
```

I have `pip` installed everything from `requirements-full.txt`, `peewee` and `feedparser` into a Python 2.7.3 virtualenv.

Regards, Martin.
